---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: dxhelpdeskbot
        tier: bot
    spec:
      containers:
      - name: bot
        image: dxhelpdeskbot/bot
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: bot
  labels:
    app: dxhelpdeskbot
    tier: bot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: dxhelpdeskbot
    tier: bot