//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXHelpDeskBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXHelpDeskBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services.
        /// </summary>
        internal static string AICognitiveServices {
            get {
                return ResourceManager.GetString("AICognitiveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Learning.
        /// </summary>
        internal static string AIDeepLearning {
            get {
                return ResourceManager.GetString("AIDeepLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Learning.
        /// </summary>
        internal static string AIMachineLearning {
            get {
                return ResourceManager.GetString("AIMachineLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-Platform Development.
        /// </summary>
        internal static string ClientCross {
            get {
                return ResourceManager.GetString("ClientCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Development.
        /// </summary>
        internal static string ClientGame {
            get {
                return ResourceManager.GetString("ClientGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Development.
        /// </summary>
        internal static string ClientWeb {
            get {
                return ResourceManager.GetString("ClientWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Development.
        /// </summary>
        internal static string ClientWindows {
            get {
                return ResourceManager.GetString("ClientWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string CloudAccount {
            get {
                return ResourceManager.GetString("CloudAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers, Microservices, Orchestration.
        /// </summary>
        internal static string CloudContainers {
            get {
                return ResourceManager.GetString("CloudContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IaaS and Compute.
        /// </summary>
        internal static string CloudIaaSAndCompute {
            get {
                return ResourceManager.GetString("CloudIaaSAndCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Integration.
        /// </summary>
        internal static string CloudIntegration {
            get {
                return ResourceManager.GetString("CloudIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Of Things.
        /// </summary>
        internal static string CloudIoT {
            get {
                return ResourceManager.GetString("CloudIoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring + Management.
        /// </summary>
        internal static string CloudMonitorManagement {
            get {
                return ResourceManager.GetString("CloudMonitorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        internal static string CloudNetworking {
            get {
                return ResourceManager.GetString("CloudNetworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaaS (Web, Mobile, ...).
        /// </summary>
        internal static string CloudPaaS {
            get {
                return ResourceManager.GetString("CloudPaaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security + Identity.
        /// </summary>
        internal static string CloudSecurityIdentity {
            get {
                return ResourceManager.GetString("CloudSecurityIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data + Analytics.
        /// </summary>
        internal static string DataAnalytics {
            get {
                return ResourceManager.GetString("DataAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database (SQL, NoSql, Cache) + Storage.
        /// </summary>
        internal static string DataDatabaseAndStorage {
            get {
                return ResourceManager.GetString("DataDatabaseAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string MainAI {
            get {
                return ResourceManager.GetString("MainAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Development.
        /// </summary>
        internal static string MainClient {
            get {
                return ResourceManager.GetString("MainClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        internal static string MainCloud {
            get {
                return ResourceManager.GetString("MainCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data and Storage in the Cloud.
        /// </summary>
        internal static string MainDataStorage {
            get {
                return ResourceManager.GetString("MainDataStorage", resourceCulture);
            }
        }
    }
}
